config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tweets
  
  root 'tops#main'
  get 'tops/main'
  post 'tops/login'
  get 'tops/logout'
  
  resources :likes
  #post 'likes', to: 'likes#create'
  #delete 'likes/:id', to: 'likes#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :likes, dependent: :destroy
    has_many :like_users, source: :user, through: :likes
    
    def like(user)
        likes.create(user_id: user.id)
    end

    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end

    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
    validates :uid, presence: true
    validates :password, presence: true, confirmation: true
    
    attr_accessor :password, :password_confirmation
    
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
    
    has_many :tweets, dependent: :destroy #ユーザを消すとツイートも消える
    has_many :likes, dependent: :destroy #ユーザを消すといいねも消える
    has_many :like_tweets, source: :tweet, through: :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_user
            if session[:uid]
                User.find_by(uid: session[:uid])
            end
        end
        helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    unless tweet.liked?(current_user)
      tweet.like(current_user)
    end
   redirect_to tweets_path
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.liked?(current_user)
      tweet.unlike(current_user)
    end
    redirect_to tweets_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def main
    if session[:uid]
      render 'main'
    else
      render 'login'
    end
  end
  
  def login
    user = User.find_by(uid: params[:uid])
    if user
      login_password = BCrypt::Password.new(user.pass)
      if login_password == params[:pass]
        session[:uid] = user.uid
        redirect_to tops_main_path
      else
        render 'login'
      end
    else
      render 'login'
    end
  end
    
  def logout
      session.delete(:uid)
      redirect_to tops_main_path
  end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    logger.debug @tweets.count
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    user = User.find_by(uid: current_user)
    tweet = Tweet.new(message: params[:tweet][:message], user_id: user.id)
    tweet.save
    redirect_to tweets_path #"/**"
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to tweets_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    logger.debug @users.count
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(uid: params[:user][:uid], password: params[:user][:password], password_confirmation: params[:user][:password_confirmation])
    if @user.save
      redirect_to users_path #"/**"
    else
      render 'new'
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/tops/login.html.erb
<%= link_to 'ツイートページ', tweets_path %><br>

<%= form_tag '/tops/login', method: :post do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>

<%= link_to 'ユーザー登録', new_user_path %><br>

app/views/tops/main.html.erb
<%= link_to 'ツイートする', new_tweet_path %>
<%= link_to 'ログアウト', tops_logout_path %>

app/views/tweets/index.html.erb
<% @tweets.each do |my| %>
   <p> 
       <%= my.message %>
       <%= link_to '削除', "/tweets/#{my.id}", method: :delete %>
       
       <% if session[:uid] %>
           <% if my.likes.count == 0 %>
               <%= link_to '♡', likes_path(tweet_id: my.id), method: :post %>
            <% else %>
                <%= link_to '♥', like_path(my), method: :delete %>
            <% end %>
        <%end%>
    </p>
<% end %>

<% if session[:uid] %>
    <%= link_to 'ツイートする', new_tweet_path %>
<% else %>
    <%= link_to 'ログイン', tops_login_path %>
<%end%>
<p><%= link_to 'ユーザー一覧', users_path %></p>

app/views/tweets/new.html.erb
<%= form_for @tweet, url: {action: :create} do |f| %>
    <%= f.label :message, 'メッセージ' %>
    <%= f.text_area :message %>
    <%= f.submit '追加' %>
<%end%>

app/views/users/index.html.erb
<% @users.each do |my| %>
   <p> 
       id: <%= my.uid %>
       pass: <%= my.pass %>
       <%= link_to '削除', user_path(my.id), method: :delete %>
    </p>
<% end %>

<p><%= link_to '新規ユーザ追加', new_user_path %></p>
<p><%= link_to 'ツイートする', new_tweet_path %></p>
<p><%= link_to 'ツイート一覧', tweets_path %></p>
<p><%= link_to 'ログイン', tops_login_path %></p>

app/views/users/new.html.erb
<%= form_for @user , url: {action: :create} do |f| %>
    <%= f.label :uid, 'id' %>
    <%= f.text_area :uid %>
    <%= f.label :password, 'パスワード' %>
    <%= f.text_area :password %>
    <p>
        <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation %>
    </p>
    <%= f.submit '追加' %>
<%end%>